insert into public.catalog_products (
    id, source, provider_item_id, name, price_cop, original_price_cop,
    category, room, images, badge, description, stock, type, status, published_at
) values
    ('1', 'seed', null, 'Proyector de Nebulosa Estrellas', 89900, 129900,
     'proyectores', 'dormitorio',
     array['/images/products/nebula-1.jpg','/images/products/nebula-2.jpg','/images/products/nebula-3.jpg'],
     'sale',
     'Transforma tu habitación en un cielo estrellado con nuestro proyector de nebulosa. Con 16 colores, control remoto y temporizador. Perfecto para crear un ambiente mágico de relajación.',
     24, 'proyector', 'published', now()),
    ('2', 'seed', null, 'Tira LED RGB 5m para TV', 45000, 65000,
     'tiras-led', 'sala',
     array['/images/products/led-strip-1.jpg','/images/products/led-strip-2.jpg','/images/products/led-strip-3.jpg'],
     'sale',
     'Tira LED RGB de 5 metros con control por app y sincronización musical. Adhesivo 3M de alta calidad. Compatible con Alexa y Google Home.',
     56, 'tira-led', 'published', now()),
    ('3', 'seed', null, 'Lámpara Luna 3D', 72000, null,
     'lamparas', 'dormitorio',
     array['/images/products/moon-lamp-1.jpg','/images/products/moon-lamp-2.jpg','/images/products/moon-lamp-3.jpg'],
     'new',
     'Réplica exacta de la luna impresa en 3D con 16 colores. Incluye base de madera, control remoto y carga USB. Diámetro de 15cm.',
     18, 'lampara', 'published', now()),
    ('4', 'seed', null, 'Panel LED Hexagonal para Pared', 110000, 145000,
     'paneles', 'gaming',
     array['/images/products/hex-panel-1.jpg','/images/products/hex-panel-2.jpg','/images/products/hex-panel-3.jpg'],
     'sale',
     'Set de 6 paneles LED hexagonales modulares con control táctil. Reactivos al sonido con más de 300 combinaciones de colores. Ideales para setups gaming.',
     12, 'panel', 'published', now()),
    ('5', 'seed', null, 'Guirnalda LED Exterior 10m', 58000, null,
     'guirnaldas', 'cocina',
     array['/images/products/garland-1.jpg','/images/products/garland-2.jpg','/images/products/garland-3.jpg'],
     'new',
     'Guirnalda de luces LED cálidas de 10 metros resistente al agua (IP65). 100 LEDs de luz cálida. Perfecta para terrazas, jardines y eventos.',
     42, 'guirnalda', 'published', now()),
    ('6', 'seed', null, 'Lámpara de Atardecer 360°', 68000, 89000,
     'lamparas', 'sala',
     array['/images/products/sunset-1.jpg','/images/products/sunset-2.jpg','/images/products/sunset-3.jpg'],
     'sale',
     'Proyector de luz tipo atardecer con rotación 360°. Crea un efecto de golden hour en cualquier espacio. USB recargable con 4 modos de iluminación.',
     31, 'lampara', 'published', now()),
    ('7', 'seed', null, 'Tira LED Neon Flex 3m', 95000, null,
     'tiras-led', 'gaming',
     array['/images/products/neon-flex-1.jpg','/images/products/neon-flex-2.jpg','/images/products/neon-flex-3.jpg'],
     'new',
     'Tira LED tipo neón flexible de 3 metros. Efecto neón suave y continuo. Incluye control remoto con 120+ modos de color. Ideal para decoración gaming.',
     20, 'tira-led', 'published', now()),
    ('8', 'seed', null, 'Lámpara Cristal de Roca LED', 125000, 159000,
     'lamparas', 'sala',
     array['/images/products/crystal-1.jpg','/images/products/crystal-2.jpg','/images/products/crystal-3.jpg'],
     null,
     'Elegante lámpara de cristal de sal del Himalaya con base LED de colores. Purifica el aire y crea un ambiente de spa en tu hogar. Incluye cable USB.',
     15, 'lampara', 'published', now())
on conflict (id) do nothing;
